### ISSUE TITLE
Pod pos CrashLoopBackOff

### ISSUE THREAD

**Issue by colussim** [vmwarecloudadvocacy/acme_fitness_demo#17]
Hi,
I encounter a problem when deploying on k8s (1.19.2) the pos pod is in CrashLoopBackOff mode.
when I look at the log the message is as follows  :

2021/03/10 15:43:54 FRONTEND_HOST is set to frontend.default.svc.cluster.local
2021/03/10 15:43:54 DATASTORE is set to REMOTE
2021/03/10 15:43:54 HTTP_PORT is set to 7777
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] Loaded HTML Templates (2): 
        - 
        - index.tmpl

[GIN-debug] GET    /assets/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /assets/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
2021/03/10 15:43:54 Get http://frontend.default.svc.cluster.local/products: dial tcp: lookup frontend.default.svc.cluster.local on 10.96.0.10:53: no such host

I have access to the portal.

Do you have an idea of the problem ?

Thanks,

Emmanuel

**Comment by ghost** [comment]
I encounter the same problem, finally I solved by set **FRONTEND_HOST** value to `'frontend.<my-deploy-namespce>.svc.cluster.local'` (`frontend.default.svc.cluster.local` by default) in [point-of-sales-total.yaml](https://github.com/vmwarecloudadvocacy/acme_fitness_demo/blob/46baf6955e3ede4a0cb6b5aaae6555a70ca6932e/kubernetes-manifests/point-of-sales-total.yaml#L50) and change the image version in this file to `gcr.io/vmwarecloudadvocacy/acmeshop-pos:v0.1.2-beta`

**Comment by colussim** [comment]
Thanks
